p = "p"
mp = "mp"
pp = "pp"
ppp = "ppp"
pppp = "pppp"
f = "f"
mf = "mf"
ff = "ff"
fff = "fff"

dot = {
    "C2": "24",
    "xC2": "25",
    "D2": "26",
    "xD2": "27",
    "E2": "28",
    "F2": "29",
    "xF2": "30",
    "G2": "31",
    "xG2": "32",
    "A2": "33",
    "xA2": "34",
    "B2": "35",
    "C3": "36",
    "xC3": "37",
    "D3": "38",
    "xD3": "39",
    "E3": "40",
    "F3": "41",
    "xF3": "42",
    "G3": "43",
    "xG3": "44",
    "A3": "45",
    "xA3": "46",
    "B3": "47",
    "C4": "48",
    "xC4": "49",
    "D4": "50",
    "xD4": "51",
    "E4": "52",
    "F4": "53",
    "xF4": "54",
    "G4": "55",
    "xG4": "56",
    "A4": "57",
    "xA4": "58",
    "B4": "59",
    "C5": "60",
    "xC5": "61",
    "D5": "62",
    "xD5": "63",
    "E5": "64",
    "F5": "65",
    "xF5": "66",
    "G5": "67",
    "xG5": "68",
    "A5": "69",
    "xA5": "70",
    "B5": "71",
    "C6": "72",
    "xC6": "73",
    "D6": "74",
    "xD6": "75",
    "E6": "76",
    "F6": "77",
    "xF6": "78",
    "G6": "79",
    "xG6": "80",
    "A6": "81",
    "xA6": "82",
    "B6": "83",
    "C7": "84",
    "xC7": "85",
    "D7": "86",
    "xD7": "87",
    "E7": "88",
    "F7": "89",
    "xF7": "90",
    "G7": "91",
    "xG7": "92",
    "A7": "93",
    "xA7": "94",
    "B7": "95",
    "C8": "96",
    "xC8": "97",
    "D8": "98",
    "xD8": "99",
    "E8": "100",
    "F8": "101",
    "xF8": "102",
    "G8": "103",
    "xG8": "104",
    "A8": "105",
    "xA8": "106",
    "B8": "107",
}


def command():
    """
    /summon minecraft:falling_block ~ ~1 ~ {id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:command_block"},Passengers:[{id:"minecraft:falling_block",Time:1,DropItem:0,BlockState:{Name:"minecraft:redstone_block"},Motion:[0d,-1d,0d]}],Motion:[0d,-1d,0d],TileEntityData:{auto:0,Command:"/setblock ~ ~2 ~ minecraft:command_block{auto:1,Command:\"fill ~ ~ ~ ~ ~-64 ~ air\"} replace"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:0,Command:""}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p74ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p83ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p67ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p62ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p55ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p62ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p67ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p62ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p55ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p62ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p67ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p62ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p55ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p62ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p67ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p62ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p55ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p62ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p67ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p62ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p55ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p62ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p67ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p62ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p55ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p62ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p67ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p62ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p55ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p62ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p67ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p60ff block @p ~ ~ ~ 2 1"}}],Motion:[0d,-1d,0d],TileEntityData:{auto:1,Command:"/playsound lkrb.piano.p62ff block @p ~ ~ ~ 2 1"}}]}
    """
    return False
